### PR TITLE
Fix search bar so that it goes to the new themed docs rather than the RTD full text search (as theme is different)

### PR DESCRIPTION
**Pull request by astrofrog**
@eteq - we should probably merge this before 0.1

### CODE REVIEW

**Comment by eteq** [comment]
I don't understand this - didn't we change this in #5 because there were problems with the sphinx one?

Also, the URL you're using here is for "latest" - e.g. the current _development_ docs... do we want the stable one, or was that intended?

**Comment by astrofrog** [comment]
RTD has a special search URL - try going to astropy.org and search, and you'll see what I mean. That is the full-text RTD search, not the sphinx search. But now that we don't use the RTD theme, it might not make sense to use that, so this PR fixes that so it uses the normal sphinx search.

The search doesn't work for the stable URL yet, so this will need updating again once we release. I guess we can wait until then to fix it since it's < 1 day :-) So let's hold off merging this.

**Comment by eteq** [comment]
Sounds good - it might be there's a way to point to the default when it's not latest... I'll look into that once the release is actually done.

**Comment by astrofrog** [comment]
@eteq - we forgot to do this for 0.1 - oops! Let's do it for 0.2! (we have to update the website anyway for 0.2)

**Comment by eteq** [comment]
yeah, sounds good - we'll try to get all PRs here (just 2 right now, but who knows...) cleaned out before we update the site for 0.2.

**Comment by astrofrog** [comment]
@eteq - just updating this before we update the website build

**Comment by eteq** [comment]
now it points to "latest" - is that what we want (rather than v0.2)?

**Comment by astrofrog** [comment]
Just fixed that :-) Good to merge?

**Comment by eteq** [comment]
Looks good! Merging.  I'll do a quick check of this on my github page, and if nothing seems broken, I'll upload it to astropy.org

**Pull request merged**
