### PR TITLE
Add pypy_name for specutils

### PR DESCRIPTION
**Pull request by cdeil**
https://github.com/astropy/specutils/issues/26
https://pypi.python.org/pypi/specutils/

### CODE REVIEW

**Comment by wkerzendorf** [comment]
looks good to me.

**Comment by cdeil** [comment]
The change is not showing up yet.
Is there an extra step needed for http://affiliated.astropy.org/registry.json to update?
Do we need to ping someone or does this happen automatically (e.g. nightly or something)?

**Comment by eteq** [comment]
@cdeil - just saw this now.  To get it to actually show up on the web page, someone has to run the upload script to make it update the actual web site.  Right now that means me, @astrofrog, or @kbarbary

**Comment by eteq** [comment]
Oh, and it should be up now, as I just uploaded it.

**Comment by astrofrog** [comment]
There was a typo, `pypy_name` should be `pypi_name` - fixed in 48da42127f69bb8919ada4229d0c45ac0309d114

**Pull request merged**
