### PR TITLE
User-friendly page for affiliated packages

### PR DESCRIPTION
**Pull request by astrofrog**
The affiliated package page, linked from the home page, now 'features' released and stable affiliated packages, and also mentions packages in development. A link to the actual registry is also included.

cc @kbarbary @eteq

### CODE REVIEW

**Comment by kbarbary** [comment]
The new index page looks nice. What is the wisdom of having both the index.html page and the registry.html page? I think the duplication will be confusing. Can we just put the generated table from registry.html in place of the "In Development" section? (and rename the section "All affiliated packages" or something)

Minor comments:
- `python-montage` vs `montage-wrapper`... two names for the same thing?
- Should `astroML` be given a blurb? or listed somewhere? It is "stable".

**Comment by eteq** [comment]
I definitely look the new look, @astrofrog, but I was going to say the exact same thing as @kbarbary even before I saw he said it: I think it makes sense to keep the registry table on the `index.html` page, just at the bottom.

@kbarbary second question brings up a secondary question: what should we do with future "stable" packages that aren't necessarily flashy or as fleshed out as the others?  Maybe add a `stable` section in just list form, like the current `in development`?

**Comment by astrofrog** [comment]
@eteq @kbarbary - I've merged the pages.

I think maybe we could set the rule that to be 'featured', a package has to reasonably meet the expectations for affiliated packages - by that I mean that e.g. AstroML is still requiring PyFITS, so in that sense it is not 'complete' as an affiliated package. One could similarly require e.g. good documentation, tests, etc. 

If that sounds reasonable, then I can change the name of the first section to 'Featured packages' and then below have a section on 'Other stable packages'? (we can add a blurb about what the distinction between the two is). What do you think?

I guess the real question is whether we require any criteria for a package to be an affiliated package. None of the affiliated packages so far have gone through any review process, so that's why I'm suggesting still having some kind of quality control, but at the level where we recommend/feature packages.

**Comment by astrofrog** [comment]
Also, RST is not letting me have a "Home" link for each package unless it's called something different, hence the long link names. Any idea on how to get around this?

**Comment by eteq** [comment]
@astrofrog - The merged version looks good.  

On your question, I suggest we merge this, and then address that as a separate item, for which I've created #42.  We (you, me, and Perry) should probably finalize on the criteria (with community input), as we're nominally the gatekeepers.

I'm also +1 to your idea of the "featured" and "other" packages. For now, I'd say we should leave off the specific description of what that means.  #42 should have that, but I'd say we wait on that until this is merged.

By the way, should we consider this as closing #13 when it's merged? (And I presume this closes #40, as that's what I think it was prompted by?)

**Comment by eteq** [comment]
Oh, and re: @astrofrog's question about "Home" links.  By this you mean you just want the link text to be "Home" instead of e.g. "Montage-wrapper Home", right?  And the problem is that it complains because you're re-using the same link name?  One solution is to just use inline links (e.g. ``Home <http://...>`_`), but that might make the tables start to get really hard to read.  The better one is probably to use ReST substitution.  For Montage-wrapper, that would look like this:

```
Montage-wrapper
---------------

.. |mont| image:: montage.png

.. |monthome| replace:: Home
.. _monthome: http://www.astropy.org/montage-wrapper
.. _Montage-wrapper Documentation: http://montage-wrapper.readthedocs.org/
.. _Montage-wrapper Installation: http://montage-wrapper.readthedocs.org/en/latest/#installation

+--------+----------------------------------------------------------------------------------+
| |mont| | **About:** Montage-wrapper is a pure Python module that provides a               |
|        | Python API to the Montage Astronomical Image Mosaic Engine,                      |
|        | including both functions to access individual Montage commands,                  |
|        | and high-level functions to facilitate mosaicking and                            |
|        | re-projecting. Python-montage uses the Astropy core package for                  |
|        | reading and writing FITS files.                                                  |
|        |                                                                                  |
|        | **Developer:** Thomas Robitaille                                                 |
|        |                                                                                  |
|        | |monthome|_ - `Montage-wrapper Documentation`_ - `Montage-wrapper Installation`_ |
|        |                                                                                  |
+--------+----------------------------------------------------------------------------------+
```

Of course, you could replace the "Documentation" and "Installation" items the same way as I did "Home" here, but I just did "Home" as an example.

**Comment by astrofrog** [comment]
@eteq - thanks for the tip, fixing now. Will answer the other questions once that's done.

**Comment by astrofrog** [comment]
I've now fixed the layout and the long links. I've also created the 'featured' and 'other' sections. I agree we can defer clarifying the rules until #42, and we can also close #13.

@eteq - does this look good to merge?

**Comment by kbarbary** [comment]
For what it's worth, the unofficial criteria for being a "featured package" sound good to me.

Also, I'm in favor of keeping the bar low for being considered an "affiliated package" of some sort. It's good to have people listing their work here as a record of what's out there and being developed, even if it isn't ready for use.

**Comment by eteq** [comment]
@astrofrog  - Looks good to me! I'll merge this then, close #13 and push it up to the site. Should we also close #40?

@kbarbary - feel free to comment on this in #42 once there's something there - I see your point, but I think we also want at least _some_ standards (or possibly a rule that removes them if they don't work towards common goals).  Anyway, needs more thought.

**Comment by eteq** [comment]
whoops... looks like something here broke the javascript for the registry table on the live site.  I'll look into it and try to fix it in master.

**Comment by eteq** [comment]
Ah, figured it out - the javascript from before assumed there was only one `<table>` on the page, which is now not true, but the change in astropy/astropy-website@548f4ecc8a7310fb1ccb6d732f52994a6e61f279 makes it now work fine.

**Pull request merged**
