### PR TITLE
Updated "The Team" link to point to devdocs

### PR DESCRIPTION
**Pull request by eteq**
This is intended to be merged along side astropy/astropy#775 .  It adjusts the "The Team" link to point to the astropy (dev) docs author list instead of having a parallel one.  The idea is that this way we only need to keep one list up-to-date.

Two questions about this:
1. Right now it's pointed to the latest/development docs.  It would be a trivial change to instead have it use the list from the latest _released_ version.  I mildly prefer the dev version, because it's the most up-to-date.
2. Click the "The Team" link now means that the top header changes to match the astropy docs instead of the header for the page.  This is not a big deal because the style is similar, but it's marginally jarring.  Is there any way to use the webpage css with the doc page content? (Or is that violating some important security sandboxing?)

@astrofrog @kbarbary

### CODE REVIEW

**Comment by astrofrog** [comment]
@eteq - the issue with sending people to the latest dev docs is that they may not realize they are in those rather than in the latest stable docs, but then I also agree that it'd be nice to send people to the latest list. So I think there's an issue here.

One alternative to this solution would therefore be to keep the team page _only_ on the website (which has only one version, the latest), and have the link in the docs point to the website. Yes, it does mean we have to remember to update the list, but we've not really been updating that list anyway in parallel with the code, so maybe there's no difference from that point of view. We could even set up a cron job on a computer that will check if a commit in the core repository comes from a new user, and send us email alerts, so we can update the website? That would be easy to do, right? If we do this, it also solves the change in the top header.

**Comment by eteq** [comment]
@astrofrog - I don't think we want the _only_ copy to be on the web site, because then it's not in the source code, and I think we should always have an author list in the source code that we distribute.

I see your point about people getting "lost" by getting redirected to the dev docs.  So that probably means it's better to figure out a way to do the # 2 I mentioned above.  If we can't do it directly as I described there (perhaps some javascript magic?), we could also add a script to this repo that pulls the `credits.rst` file from astropy's master, and have that run in the makefile for building the web site. 

In any of those cases, a cron job that sends an email when a new committer appears might be a good idea - regardless of where the list is, we should probably try to keep it up to date.

**Comment by astrofrog** [comment]
@eteq - I'm liking your idea of having the website builder pull credits from the code. Then credits.rst still lives in the docs, or just at the root level of the package? (no strong opinion, just curious). I'd personally prefer that over some kind of javascript/AJAX magic.

**Comment by eteq** [comment]
I was thinking leave the astropy repo exactly as is (`docs/credits.rst`) so that we don't have to do anything weird to get sphinx to build those docs correctly.  It would be easy enough to just pull that directly from github in the makefile.

I'll adjust this PR (or make a new one in astropy-website) to do something like that, then.   astropy/astropy#775 is already merged, so I can test it directly, now.

**Comment by astrofrog** [comment]
Ok, that sounds good!

**Comment by kbarbary** [comment]
Good solution guys.

**Comment by eteq** [comment]
This is now implemented in #20 , so I'll close this.

**Pull request closed without merging**
