### PR TITLE
Added feedback page

### PR DESCRIPTION
**Pull request by keflavich**
Added a draft feedback page as per https://github.com/astropy/astropy/issues/1457.

To Do:
- [x] Link feedback.astropy.org to this page
- [ ] Create feedback@astropy.org e-mail address
- [ ] Make feedback@astropy.org redirect to astropy-feedback@googlegroups.com

I can't do either of those.

### CODE REVIEW

**Comment by keflavich** [comment]
Also, I was going to raise this as another issue, but it would be nice if we could figure out how to include linked e-mail address in page footer.  Astroquery now has an e-mail address in the footer, but it is plaintext instead of a URL, and trying to manually wrap it in html tags didn't work.

**Comment by eteq** [comment]
You know, it might be better to.

Re: the e-mail address... I'm not entirely sure this is possible.  Because we don't have our own server for astropy.org (it's github pages), we can't forward it from there, so we'd either have to set up a server specifically for this or try to do some redirect magic directly to astropy-feedback@googlegroups.com, which I think google frowns on due to spamming (I could test it and see, though).  Alternatively, this can just tell people to email directly to astropy-feedback@googlegroups.com for now, and later we could add a web form to do this.

Also, has anyone (@demitri @astrofrog @keflavich @embray @mdboom) created the astropy-feedback google group already?  I just tried to right now and it said it's already taken...

**Comment by keflavich** [comment]
I'm fairly sure @astrofrog registered astropy-feedback on Thursday.

I think it's fine to have users e-mail astropy-feedback@googlegroups.com.  feedback@astropy.org was just a pretty cover for that.

**Comment by eteq** [comment]
Alright, sounds good. 

I just set it up so that http://feedback.astropy.org redirects to http://www.astropy.org/feedback .  So if you just change the name of the file you've added here from `feedback.rst` to `index.rst`, it will all work as soon as this is merged and pushed up.

**Comment by taldcroft** [comment]
Should this page also reference the other two acceptable channels of providing "feedback":
- astropy-dev
- github issues

I suggest this because http://feedback.astropy.org could end up as the most popular single entry point for people wanting to know how to file bug reports etc.  For instance any 3rd party pages/blogs, talks, etc might say "And if you want to give the Astropy project feedback of any sort, go to http://feedback.astropy.org".  

This link should also be incorporated into the main astropy sphinx docs:
http://astropy.readthedocs.org/en/latest/index.html#getting-help
http://astropy.readthedocs.org/en/latest/index.html#reporting-issues

**Comment by keflavich** [comment]
@eteq - anything more I should do on this?  I think it should be merged _before_ the site rewrite - I've received a request from a (former) local colleague asking "Where do I go for help [now that you're gone]?" and I'd like to give a definitive answer.

**Comment by astrofrog** [comment]
We still need to set up `feedback@astropy.org`, right? @eteq do you know how to do that?

**Comment by eteq** [comment]
@keflavich @astrofrog - as I said before, I don't think it's possible to do `feedback@astropy.org` without having our own web server. So I think above we agreed to just change it to astropy-feedback@googlegroups.com, right?

**Comment by astrofrog** [comment]
@eteq - actually godaddy allows you to set up forwarding email addresses (I did it for another domain). I think it's free for the first x email addresses.

**Comment by astrofrog** [comment]
But feel free to just use the google groups address for now.

**Comment by eteq** [comment]
@astrofrog - my impression was that you had to pay extra for email (the sidebar for astropy.org says "not purchase" under email).  But it might just be that I can't do it because I'm an admin and not the actual owner? Or I might just not be able to navigate godaddy's interface...

**Comment by astrofrog** [comment]
@eteq - let's go with the google groups address for now, and we can always add the alias later if we figure out how.

**Comment by demitri** [comment]
Is it just me, or is making feedback publicly visible a little strange? I don't think this is the best plan, but in lieu of something better in the meantime, I think it should be made _very clear_ that feedback sent to astropy will be publicly visible, with your name attached to it. I don't think this is optimal.

**Comment by keflavich** [comment]
I certainly don't think the feedback e-mails should be public; where does astropy-feedack go?  If it redirects to astropy-dev, that is certainly too public - perhaps it should go to the coordinating committee, with other members added at their discretion?

**Comment by astrofrog** [comment]
The astropy-feedback group is only visible to members, which have to be invited by hand, so all feedback will be private.

**Comment by astrofrog** [comment]
And it doesn't get forwarded to astropy-dev

**Comment by demitri** [comment]
@astrofrog Cool, sounds good.

**Comment by eteq** [comment]
Alright, great, so is this all ready to merge as far as you're concerned, @keflavich ?

**Comment by keflavich** [comment]
Think so.  Any further changes can be PR'd later.

On Tue, Oct 15, 2013 at 10:43 PM, Erik Tollerud notifications@github.comwrote:

> Alright, great, so is this all ready to merge as far as you're concerned,
> @keflavich https://github.com/keflavich ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/astropy/astropy-website/pull/49#issuecomment-26370457
> .

## 

Adam

**Comment by eteq** [comment]
Alright, then I'll merge and update the site.  Thanks @keflavich and @demitri !

**Pull request merged**
