### PR TITLE
Updated logos to new versions

### PR DESCRIPTION
**Pull request by astrofrog**
This implements the new logos from

astropy/astropy-logo#1

Try and build the site on this fork and let me know what you think.

cc @kbarbary @eteq

### CODE REVIEW

**Comment by eteq** [comment]
Looks good to me!

**Comment by astrofrog** [comment]
Since these changes are trivial now that the astropy-logo PR has been merged, I'm merging this.

**Comment by astrofrog** [comment]
I will see to updating the website build (with your script)

**Comment by astrofrog** [comment]
The build has been updated, and http://www.astropy.org/ shows the new logos

**Comment by kbarbary** [comment]
Looks good!

**Pull request merged**
