### PR TITLE
Update text on front page

### PR DESCRIPTION
**Pull request by eteq**
This is just a reminder to update the content on the homepage to reflect 0.2.

I was also wondering whether it would make sense to reword _The Astropy project is a common effort to develop a single core package for Astronomy that brings together almost 100 developers from around the world._ as '100 developers' is a little ambiguous - we have 130-140 people on the dev list, but only ~30 developers have actually contributed code. Maybe we should just say _The Astropy project is a community effort to develop a single core package for Astronomy._ and then merge into the start of the 2nd paragraph.

### CODE REVIEW

**Comment by astrofrog** [comment]
I'll try and do this tomorrow evening (european time) but if you have time before that, feel free to do it too. Once the official release is ready and on PyPI, we can merge all these in and update the website build.

**Comment by eteq** [comment]
@astrofrog - how do the attached changes look?

**Comment by astrofrog** [comment]
Looks good! Merging :)

**Pull request merged**
