### PR TITLE
Added initial version of affiliated package repository

### PR DESCRIPTION
**Pull request by astrofrog**
This is the initial version of the affiliated package registry. When the sphinx docs are built, this will be placed in http://www.astropy.org/affiliated/registry.json, and we can get affiliated.astropy.org to point to astropy.org/affiliated.

### CODE REVIEW

**Comment by astrofrog** [comment]
Is astropysics currently an affiliated package? I'm planning on migrating ATpy and APLpy to affiliated packages, so I'll add those as stable examples once that's done.

**Comment by eteq** [comment]
Yes, it is. Whether you consider it "stable" or not depends on your definition of stable, I guess :)

**Comment by astrofrog** [comment]
I guess I meant whether they could be installed from a tarfile which should guarantee some degree of stability since people usually release tar files they expect will install (as opposed to the packages which don't have tar files, and for which anything might happen when they are installed from the repo). Maybe it's redundant with the `tarfile_url` field though (i.e if that field is there, it can probably be considered stable?).

**Comment by eteq** [comment]
Now that I think about it, it might be more sensible to remove the `tarfile_url` butleave in `stable` - the problem with `tarfile_url` is that we have to update it whenever a version changes.  If there's a unique pypi name, it makes the most sense to use that to get the download link (either by browsing manually or using the pypi rpc stuff).  a `tarfile_url` (or perhaps just "download_url" to allow .zip sometimes) I would think should be given only if it's _not_ on pypi

**Comment by astrofrog** [comment]
Good point about having to update the URLs at every release - I've removed `tarfile_url`.

**Comment by astrofrog** [comment]
By the way, we can merge this in as soon as you are ok with it, and I'll just add ATpy and APLpy once they are ready. Bear in mind that we could delay having the installer in the core package until just after the 0.1.0 release, which will give us more time to experiment with it until the next stable release?

**Comment by eteq** [comment]
@astrofrog - that sounds reasonable.  We can also include in there documentation about exactly what the fields are for this JSON file. Merging!

**Pull request merged**
