### PR TITLE
add pydl to affiliated package registry

### PR DESCRIPTION
**Pull request by eteq**
This adds the package pydl to the affiliated package registry as per the request of @weaverba137 to the astropy email address.

### CODE REVIEW

**Comment by astrofrog** [comment]
Could you add an entry for montage-wrapper too? (I'd do it, but I'm away and offline for the next 3 days!)

**Comment by eteq** [comment]
@astrofrog - Done, see #29

**Comment by eteq** [comment]
This now also removed the pyidlastro package.  This was discussed in #13 given the lack of activity, and the pydl developers are fine with having miscellaneous contributed community packages living there.

**Comment by weaverba137** [comment]
Note:  The 'master' branch in the pydl repository reflects how the package looked when I moved it out of another repository.  If you want to see what pydl really looks like, see the 'astropy' branch in the pydl repository.

**Comment by eteq** [comment]
Alright, I'm going to go ahead and merge this, then.

**Pull request merged**
