### PR TITLE
add menu link to affiliated page

### PR DESCRIPTION
**Pull request by kbarbary**
The affiliated package page is getting more and more important with a growing number of useful affiliated packages. Yet, I find it very difficult to locate this page.

This PR adds a menubar link to the affiliated package page. See a built preview here:
http://kbarbary.github.io/astropy-website/

### CODE REVIEW

**Comment by astrofrog** [comment]
This reminds me I had started this is #13, but wanted a more user-friendly page on the main website - preview is here:

http://astrofrog.github.io/astropy-website/

Now there are more affiliated packages I can try and make that into a pull request.

**Comment by kbarbary** [comment]
Oh great! Yeah I like that menu bar better anyway. My one comment is to copy my change to `searchbar.html` so that the searchbox lines up with the right hand margin.

**Comment by astrofrog** [comment]
Good idea - I'll try and open a pull request for this this week.

**Comment by eteq** [comment]
This is replaced by #41, right @astrofrog and @kbarbary ?

**Comment by kbarbary** [comment]
Right. Closing!

**Pull request closed without merging**
